module.exports = {
    start: ["[narrator:#narratorNames#][character1:#names#]#story#"],
    playerName: ["stranger", "wanderer", "newcomer", "visitor", "newcomer", "foreigner", "outlander", "outsider", "friend",],
    story: ["Welcome to my corner of the woods #playerName#. It's #embellishment# #feeling# #timeOfDay#. Can you help me start this here fire by blowing on your microphone?"],
    embellishment: ["so", "extremely", "very", "disturbingly", "horrendously", "unusually"],
    timeOfDay: ["tonight", "this evening", "out here"],
    feeling: ["quiet", "cold", "dark", "lonely"],
    narratorNames: ["Alex", "Billy", "Doruk", "Ece", "Hugh", "Jade", "Julia", "Matthew", "Phoenix", "Raymond", "Tommy"],
    opening: ["Ah, much better. My name is #narrator#, and I've been #profession.a# out here in the #feeling# #location# for nearly #number# odd years. I have met many #playerName.s# in my day, and many with #tale.s# of their own, most of them #truth#. I'll tell you one of my favorites, but only if you help me"],
    profession: ["scout leader", "ranger", "woodworker", "hunter"],
    number: ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twenty-one", "twenty-two", "twenty-three", "twenty-four", "twenty-five", "twenty-six", "twenty-seven", "twenty-eight", "twenty-nine", "thirty"],
    location: ["forest", "woods", "national park", "backwoods", "bush", "wildwood"],
    truth: ["true"],
    tale: ["story", "tale"],
    sceneOne: ["To protect the people that are still living in this story, I'll need a name. What's one that you like?"],
    question1: ["And what is a name that you don't like?"],
    question2: ["Why did you choose those names?"],
    sceneTwo: ["#leadIn#, there was a group of #relationship.s# #reasonForBeingThere#. You would think that they were just out there for fun, but each of them had come out into the #location# to hide from what they had done."],
    reasonForBeingThere: ["camping", "hiking", "passing through", "seeking shelter"],
    relationship: ["friend", "enemy", "student", "backpacker", "vagrant", "traveler", "classmate", "aqcuaintance", "close friend", "sibling"],
    leadIn: ["Many years ago, in #location.a# just like this"],
    question3: ["What are you afraid of?"],
    question4: ["You are alone in an amusement park, what ride do you go on first?"],
    question5: ["Your neighbor has been dumping garbage on your lawn for the past few weeks. What special name have you got for him now?"],
    transition: ["You've answered all of my questions! Let's get started"],
    dreamSequence: ["Crazy effect I haven't made yet", "Fur ... EVERYWHERE", "Dinosaurs with Jetpacks. Woo"],
    warning: ["run", "get out", "help", "look out"],
    ending: ["This is one potential ending: James did many things that he was not supposed to do, and this was the worst. James was told not to use his computer, and this time he did. He went online and began to tell stories that were not true. Posting bad comments lies about others. James kept telling these stories until one day he became them, and is now telling them to you! BOO!"]
};