module.exports = {
    start: ["[narrator:#narratorNames#][character1:#names#]#story#"],
    names: ["Lucien", "Roy", "Anika", "Monica", "Kailan", "Blair", "Sam", "Jonas", "Shaun", "Vijay", "Conah", "Seema", "Paisley", "Billie-Jean"],
    playerName: ["stranger", "wanderer", "newcomer", "visitor", "newcomer", "foreigner", "outlander", "outsider", "friend",],
    story: ["Welcome to my corner of the woods #playerName#. It's #embellishment# #feeling# #timeOfDay#. Can you help me start this here fire by blowing on your microphone?"],
    embellishment: ["extremely", "very", "disturbingly", "horrendously", "unusually"],
    timeOfDay: ["tonight", "this evening", "out here"],
    feeling: ["quiet", "cold", "dark", "lonely"],
    narratorNames: ["Alex", "Billy", "Doruk", "Ece", "Hugh", "Jade", "Julia", "Matthew", "Phoenix", "Raymond", "Tommy"],
    opening: ["Ah, much better. My name is #narrator#, and I've been #profession.a# out here in the #feeling# #location# for nearly #number# odd years. I have met many #playerName.s# in my day, and many with #tale.s# of their own, most of them #truth#. I'll tell you one of my favorites, but only if you help me"],
    profession: ["scout leader", "ranger", "woodworker", "hunter"],
    number: ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twenty-one", "twenty-two", "twenty-three", "twenty-four", "twenty-five", "twenty-six", "twenty-seven", "twenty-eight", "twenty-nine", "thirty"],
    location: ["forest", "woods", "national park", "backwoods", "bush", "wildwood"],
    truth: ["true"],
    tale: ["story", "tale"],
    sceneOne: ["To protect the people that are still living in this story, I'll need a name. What's one that you like?"],
    question1: ["And what is a name that you don't like?"],
    question2: ["Why did you choose those names?"],
    sceneTwo: ["#leadIn#, there was a group of #relationship.s# #reasonForBeingThere#. You would think that they were just out there for fun, but each of them had come out into the #location# to hide from what they had done."],
    reasonForBeingThere: ["camping", "hiking", "passing through", "seeking shelter"],
    relationship: ["friend", "enemy", "student", "backpacker", "vagrant", "traveler", "classmate", "aqcuaintance", "close friend", "sibling"],
    leadIn: ["Many years ago, in #location.a# just like this"],
    sceneThree: ["[playerCharacter: #characterNames.capitalize#] #playerCharacter# was the #position# of the group. They #characterCut# and #characterCut2#. Most people would describe them as the #superAdj1# person that they have ever met"],
    characterCut: ["owned a collection of #adj1# #animal# figurines"],
    characterCut2: ["they spent their days dreaming about #dreams#"],
    characterNames: ["#likedName#", "#dislikedName#"],
    dreams: ["living abroad", "owning a bookstore", "sailing the narrow sea", "getting super fit"],
    animal: ["owl", "meerkat", "platypus", "jaguar"],
    sceneFour: ["#playerCharacter.capitalize# was told not to #forbiddenThing#. But #playerCharacter.capitalize# was #embellishment# curious, and one day they did!"],
    forbiddenThing: ["enter the old house at the end of #streetName#"],
    streetName: ["Porters Lane"],
    position: ["leader"],
    sceneFive: ["They snuck inside and began to look around, gingerly stepping upon the #adj2# ground. They thought that there must be #greed# here."],
    fear: ["clowns"],
    greed: ["treasure"],
    questionFour: ["I should tell you that #playerCharacter.capitalize# is terrified of #fear#. What are you afraid of?"],
    // sceneSix: ["test"],
    question5: ["You are alone in an amusement park, what ride do you go on first?"],
    question6: ["Your neighbor has been dumping garbage on your lawn for the past few weeks. What special name have you got for him now?"],
    question7: ["Say, you don't have anything to hide yourself, do you?"],
    transition: ["You've answered all of my questions! Let's get started"],
    dreamSequence: ["Crazy effect I haven't made yet", "Fur ... EVERYWHERE", "Dinosaurs with Jetpacks. Woo"],
    warning: ["run", "get out", "help", "look out"],
    sceneSix: ["I should tell you that I haven't been entirely truthful"],
    endingPossible: ["This is one potential ending: James did many things that he was not supposed to do, and this was the worst. James was told not to use his computer, and this time he did. He went online and began to tell stories that were not true. Posting bad comments lies about others. James kept telling these stories until one day he became them, and is now telling them to you! BOO!"]
};